apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          env:
            - name: configmap_for_app_env
              valueFrom:
                configMapKeyRef:
                  name: my-app-config # Reference to the ConfigMap
                  key: APP_ENV
            - name: secret_for_DB_password
              valueFrom:
                secretKeyRef:
                  name: my-app-secret # Reference to the ConfigMap
                  key: DB_PASSWORD
          ports:
            - containerPort: 80
